//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.HomeVisits.WebAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SW.HomeVisits.WebAPI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No requests available now.
        /// </summary>
        public static string ChemistNoScheduleFound {
            get {
                return ResourceManager.GetString("ChemistNoScheduleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost visit has successfully saved.
        /// </summary>
        public static string LostTimeSavedSuccess {
            get {
                return ResourceManager.GetString("LostTimeSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Time Zone Avialable For Second Visit After First Visit Time By Min and Max Minute.
        /// </summary>
        public static string NoTimeZoneAvialableForSecondVisit {
            get {
                return ResourceManager.GetString("NoTimeZoneAvialableForSecondVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patients available now.
        /// </summary>
        public static string PatientsNotFound {
            get {
                return ResourceManager.GetString("PatientsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no pending visits for this Patient.
        /// </summary>
        public static string PatientVisitsNotFound {
            get {
                return ResourceManager.GetString("PatientVisitsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameters Not Found.
        /// </summary>
        public static string SystemParametersNotFound {
            get {
                return ResourceManager.GetString("SystemParametersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit completed successfully.
        /// </summary>
        public static string VisitCompletedSuccessfully {
            get {
                return ResourceManager.GetString("VisitCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit details not found.
        /// </summary>
        public static string VisitDetailsNotFound {
            get {
                return ResourceManager.GetString("VisitDetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit is cancelled.
        /// </summary>
        public static string VisitIsCancelled {
            get {
                return ResourceManager.GetString("VisitIsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications available now.
        /// </summary>
        public static string VisitNotificationNotFound {
            get {
                return ResourceManager.GetString("VisitNotificationNotFound", resourceCulture);
            }
        }
    }
}
